#服务器配置
server:
  tomcat:
    uri-encoding: utf-8
  port: 5700

spring:
  #数据源
  datasource:
        url: jdbc:mysql://localhost:3306/wxpush?serverTimezone=Asia/Shanghai&characterEncoding=utf8
        username: root
        password: root

  #视图层控制
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false

#Mybatis扫描
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #起别名。可省略写mybatis的xml中的resultType的全路径
  type-aliases-package: com.wx.wxpush.entiy
